name: Send Ethereum Newsletter via Resend

on:
  schedule:
    - cron: '0 12 * * SUN'  # Every Sunday at 12:00 UTC
  workflow_dispatch:

jobs:
  send_newsletter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Send the newsletter via Resend
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          NEWSLETTER_RECIPIENT: ${{ secrets.NEWSLETTER_RECIPIENT }}
        run: |
          python send_newsletter.py
