name: Weekly Ethereum Newsletter

on:
  schedule:
    # Every Monday 12:00 UTC
    - cron: '0 12 * * 1'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    env:
      TIMESTAMP: ${{ github.run_started_at || 'manual' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install requests beautifulsoup4 PyYAML gitpython markdown2 resend

      - name: Prepare context folder
        run: mkdir -p context newsletters

      - name: Fetch Client Stats
        run: python scripts/fetch_client_stats.py

      - name: Fetch New EIPs
        run: python scripts/fetch_new_eips.py
      
      - name: Set START_DATE and END_DATE
        run: |
          echo "START_DATE=$(date -d '7 days ago' +%Y-%m-%d)" >> $GITHUB_ENV
          echo "END_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Generate Ethereum Newsletter via OpenHands
        uses: xinbenlv/openhands-action@v1.0.1-rc3
        with:
          prompt: >-
            Please summarize the latest news from the Ethereum ecosystem 
            over the past 7 days. Include updates from blog.ethereum.org, 
            ethereum/pm GitHub, ethresear.ch, and ethereum-magicians.org. 
            Emphasize major network upgrades, new EIPs, and official blog posts 
            and highlight at the top of the output. Format like WeekInEthereum 
            (https://weekinethereum.substack.com/p/week-in-ethereum-news-december-28-eb1), 
            in markdown, with all original links and references.
            
            Structure the output into the following Markdown sections:
            1. **Intro Paragraph** – Summarize the week’s key news in 1-2 sentences.
            2. **Network Upgrades** – Mainnet/testnet upgrades, core dev meeting decisions.
            3. **EIPs & Standards** – New/finalized EIPs/ERCs. Include links and status tags.
            4. **Client Releases** – Execution & consensus layer client updates, grouped separately.
            5. **Research & Development** – Notable technical research or protocol analysis.
            6. **Ecosystem & Community** – Announcements, education, programs, partnerships.
            7. **Centralization Watch** – Inject stats from context_stats.md below.
            8. **Upcoming Dates** – Events, upgrade activations, hackathons.
            
            Use concise, link-rich markdown formatting. No TL;DR. Use a serious, editorial tone. 
            Do not use emojis unless for critical alerts (e.g. centralization risk).
            Use only updates relevant to the past 7 days: from ${{ env.START_DATE }} to ${{ env.END_DATE }}.
            Ignore older news unless it had major status changes this week.

            External context:

            ```markdown
            {{ context_stats }}
            {{ context_eips }}
            ```
          files: |
            context/context_stats.md
            context/context_eips.md
          llm_api_key: ${{ secrets.LLM_API_KEY }}
          output: newsletter.md

      - name: Archive Newsletter with Timestamp
        run: cp newsletter.md newsletters/newsletter_${{ env.TIMESTAMP }}.md
      
      - name: Send Newsletter via Resend
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          NEWSLETTER_RECIPIENT: ${{ secrets.NEWSLETTER_RECIPIENT }}
        run: |
          python scripts/send_newsletter.py newsletter.md

      - name: Upload Final Markdown Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ethereum-weekly-newsletter
          path: newsletters/newsletter_${{ env.TIMESTAMP }}.md
